import React from 'react'
import {
  findDependencyRows,
  findRiskRows,
  findScoreRows,
  findTimelineRows,
  firstUsefulTables,
  getPrimitiveEntries,
} from './jsonReportModel'
import { formatBytes, getTopLevelCount, humanizeKey, previewText, shortValue, statusLabel } from './utils'

export function HandoffPanel({ input, handoff, onDownloadHandoff }) {
  const hasDownload = Boolean(onDownloadHandoff)

  return (
    <div className="agent-handoff-panel">
      <div>
        <small>Agent Input</small>
        <pre>{previewText(input, 2200)}</pre>
      </div>
      <div>
        <header>
          <small>Input Given To Next Agent</small>
          {hasDownload && (
            <button type="button" onClick={onDownloadHandoff}>
              Download Input Doc
            </button>
          )}
        </header>
        <pre>{previewText(handoff || { message: 'Final workflow output; no next agent handoff.' }, 2200)}</pre>
      </div>
    </div>
  )
}

export function AgentOutputPanel({ output, onDownloadDocument }) {
  const documentFile = output?.file
  const hasDocument = Boolean(documentFile)

  return (
    <div className="agent-output-panel">
      <header>
        <div>
          <small>Agent Output</small>
          <strong>{hasDocument ? documentFile.name : output?.fileName || 'JSON response'}</strong>
        </div>
        {hasDocument && (
          <button type="button" onClick={onDownloadDocument}>
            Download Document
          </button>
        )}
      </header>
      {hasDocument && (
        <div className="agent-document-card">
          <span>Document generated by this agent</span>
          <b>{documentFile.name}</b>
          <p>{documentFile.type || 'document'} | {formatBytes(documentFile.size)}</p>
        </div>
      )}
      <pre>{previewText(output?.agentOutput || output?.data, 6000)}</pre>
    </div>
  )
}

function ScoreBars({ rows, title }) {
  if (!rows.length) return null
  return (
    <div className="json-visual-block">
      <h4>{title}</h4>
      <div className="mini-bars">
        {rows.map((row, index) => (
          <div className="mini-bar-row" key={`${row.label}-${index}`}>
            <span>{row.label}</span>
            <div><i style={{ width: `${row.value}%` }} /></div>
            <b>{Math.round(row.value)}</b>
          </div>
        ))}
      </div>
    </div>
  )
}

function TimelineVisual({ rows }) {
  if (!rows.length) return null
  const maxDuration = Math.max(...rows.map((row) => Number(row.duration) || 1), 1)
  return (
    <div className="json-visual-block">
      <h4>Timeline View</h4>
      <div className="workflow-timeline-chart">
        {rows.map((row, index) => {
          const width = Math.max(18, ((Number(row.duration) || 1) / maxDuration) * 100)
          return (
            <div className="workflow-timeline-row" key={`${row.label}-${index}`}>
              <span>{row.label}</span>
              <div>
                <i style={{ width: `${width}%` }}>{row.duration ? `${row.duration}` : ''}</i>
              </div>
              <small>{row.end ? `${row.start} - ${row.end}` : row.start}</small>
            </div>
          )
        })}
      </div>
    </div>
  )
}

function DependencyVisual({ rows }) {
  if (!rows.length) return null
  return (
    <div className="json-visual-block">
      <h4>Dependency Map</h4>
      <div className="workflow-dependency-map">
        {rows.map((row, index) => (
          <div className="workflow-dependency-edge" key={`${row.source}-${row.target}-${index}`}>
            <span>{row.source}</span>
            <b>to</b>
            <span>{row.target}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

function DataTable({ collection }) {
  const rows = collection.rows.slice(0, 6)
  const columns = Array.from(new Set(rows.flatMap((row) => Object.keys(row)))).slice(0, 5)
  if (!rows.length || !columns.length) return null
  return (
    <div className="json-visual-block">
      <h4>{collection.label}</h4>
      <div className="visual-table-wrap">
        <table className="visual-table">
          <thead>
            <tr>{columns.map((column) => <th key={column}>{humanizeKey(column)}</th>)}</tr>
          </thead>
          <tbody>
            {rows.map((row, rowIndex) => (
              <tr key={`${collection.path}-${rowIndex}`}>
                {columns.map((column) => <td key={column}>{shortValue(row[column], 140)}</td>)}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export function VisualJsonReport({ data }) {
  const primitives = getPrimitiveEntries(data)
  const scoreRows = findScoreRows(data)
  const riskRows = findRiskRows(data)
  const timelineRows = findTimelineRows(data)
  const dependencyRows = findDependencyRows(data)
  const tables = firstUsefulTables(data)
  const hasVisuals = primitives.length || scoreRows.length || riskRows.length || timelineRows.length || dependencyRows.length || tables.length

  return (
    <div className="visual-json-report">
      {primitives.length > 0 && (
        <div className="json-facts">
          {primitives.map(([key, value]) => (
            <div key={key}>
              <small>{humanizeKey(key)}</small>
              <strong>{shortValue(value, 130)}</strong>
            </div>
          ))}
        </div>
      )}
      <ScoreBars rows={scoreRows} title="Score Snapshot" />
      <ScoreBars rows={riskRows} title="Risk Severity" />
      <TimelineVisual rows={timelineRows} />
      <DependencyVisual rows={dependencyRows} />
      {tables.map((collection) => <DataTable key={collection.path} collection={collection} />)}
      {!hasVisuals && <pre>{previewText(data)}</pre>}
      <details className="raw-json-details">
        <summary>View JSON</summary>
        <pre>{previewText(data, 10000)}</pre>
      </details>
    </div>
  )
}

export function AgentStep({ step }) {
  return (
    <article className={`workflow-step ${step.status}`}>
      <div className="step-marker" aria-hidden="true" />
      <div className="workflow-step-main">
        <strong>{step.title}</strong>
        <span>{step.summary}</span>
      </div>
      <div className="workflow-step-meta">
        <p>{step.detail || `${step.input} to ${step.output}`}</p>
        <em>{statusLabel(step.status)}</em>
      </div>
    </article>
  )
}

export function WorkflowStepper({ steps }) {
  const completedCount = steps.filter((step) => step.status === 'done').length
  const runningIndex = steps.findIndex((step) => step.status === 'running')
  const failedIndex = steps.findIndex((step) => step.status === 'failed')
  const activeIndex = runningIndex >= 0 ? runningIndex : failedIndex >= 0 ? failedIndex : Math.max(0, completedCount - 1)
  const maxIndex = Math.max(steps.length - 1, 1)
  const progress = steps.length <= 1 ? 0 : (completedCount / maxIndex) * 100
  const activePosition = steps.length <= 1 ? 0 : (activeIndex / maxIndex) * 100

  return (
    <div className={`workflow-stepper ${runningIndex >= 0 ? 'is-running' : ''} ${failedIndex >= 0 ? 'has-failed' : ''}`}>
      <div className="stepper-track" aria-hidden="true">
        <i className="stepper-fill" style={{ width: `${Math.min(100, progress)}%` }} />
        {runningIndex >= 0 && <b className="stepper-runner" style={{ left: `${activePosition}%` }} />}
      </div>
      <div className="stepper-nodes">
        {steps.map((step, index) => (
          <div className={`stepper-node ${step.status}`} key={step.id}>
            <span>{step.status === 'done' ? '✓' : index + 1}</span>
            <small>{step.title.replace(' Agent', '')}</small>
          </div>
        ))}
      </div>
    </div>
  )
}

export function AgentSummaryCard({ step, output, onOpen }) {
  if (!output) return null
  const keyCount = getTopLevelCount(output.data)
  const fileName = output.file?.name || output.fileName || 'JSON response'

  return (
    <article className="agent-report-card agent-summary-card">
      <header>
        <div>
          <p>{output.input}</p>
          <h3>{step.title}</h3>
        </div>
        <span>{fileName}</span>
      </header>
      <div className="agent-kpis">
        <div>
          <b>{keyCount}</b>
          <small>Top-level fields</small>
        </div>
        <div>
          <b>{output.elapsed}</b>
          <small>Elapsed</small>
        </div>
        <div>
          <b>{output.status}</b>
          <small>Status</small>
        </div>
      </div>
      <p className="agent-summary-text">{step.summary}</p>
      <div className="agent-input-preview">
        <small>Next agent receives</small>
        <strong>{shortValue(output.handoff?.file?.file_name || output.handoff?.files?.map((file) => file.file_name).join(', ') || 'No next agent', 150)}</strong>
      </div>
      <button type="button" className="agent-detail-button" onClick={() => onOpen(step.id)}>
        View Detail Report
      </button>
    </article>
  )
}

export function AgentReportModal({ step, output, onClose, onDownload, onDownloadDocument }) {
  if (!step || !output) return null
  const fileName = output.file?.name || output.fileName || 'JSON response'

  return (
    <div className="agent-modal-backdrop" role="presentation" onMouseDown={onClose}>
      <section
        className="agent-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="agent-modal-title"
        onMouseDown={(event) => event.stopPropagation()}
      >
        <header className="agent-modal-header">
          <div>
            <p className="eyebrow">Detailed Agent Report</p>
            <h2 id="agent-modal-title">{step.title}</h2>
            <span>{step.summary}</span>
          </div>
          <div className="agent-modal-actions">
            <button type="button" onClick={() => onDownload(step.id)}>
              Download Report
            </button>
            <button type="button" className="ghost-button" onClick={onClose}>
              Close
            </button>
          </div>
        </header>

        <div className="agent-modal-meta">
          <div>
            <small>Input</small>
            <strong>{output.input}</strong>
          </div>
          <div>
            <small>Output</small>
            <strong>{fileName}</strong>
          </div>
          <div>
            <small>Status</small>
            <strong>{output.status}</strong>
          </div>
          <div>
            <small>Elapsed</small>
            <strong>{output.elapsed}</strong>
          </div>
        </div>

        <HandoffPanel input={output.agentInput} handoff={output.handoff} onDownloadHandoff={output.handoffFile ? () => onDownloadDocument(step.id, 'handoff') : null} />
        <AgentOutputPanel output={output} onDownloadDocument={() => onDownloadDocument(step.id)} />
        <VisualJsonReport data={output.data} />
      </section>
    </div>
  )
}
